package NewLang.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int BBooleanType = 0;
  public static final int BIntegerType = 1;
  public static final int BaseType = 2;
  public static final int BinaryComparisonExpression = 3;
  public static final int BinaryExpression = 4;
  public static final int BooleanLiteral = 5;
  public static final int DivExpression = 6;
  public static final int EmptyStatement = 7;
  public static final int EqualExpression = 8;
  public static final int ExpStatement = 9;
  public static final int Expression = 10;
  public static final int GreaterEqualExpression = 11;
  public static final int GreaterThanExpression = 12;
  public static final int IfStatement = 13;
  public static final int IntegerLiteral = 14;
  public static final int Istatement = 15;
  public static final int LowerEqualExpression = 16;
  public static final int LowerToExpression = 17;
  public static final int Main = 18;
  public static final int MinusExpression = 19;
  public static final int MulExpression = 20;
  public static final int NotEqualExpression = 21;
  public static final int PlusExpression = 22;
  public static final int StatementContainer = 23;
  public static final int Variable = 24;
  public static final int VariableReference = 25;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x82c3f21d731742c2L, 0xa9382fa615afecaaL);
    builder.put(0x3d8a40f980199c23L, BBooleanType);
    builder.put(0x3d8a40f980199c22L, BIntegerType);
    builder.put(0x3d8a40f980199c14L, BaseType);
    builder.put(0x51b29a29f71ef95bL, BinaryComparisonExpression);
    builder.put(0x2bba03e50417871dL, BinaryExpression);
    builder.put(0xe7bf19b9812c481L, BooleanLiteral);
    builder.put(0x2bba03e5041803c2L, DivExpression);
    builder.put(0x9729f9cf414b63dL, EmptyStatement);
    builder.put(0x51b29a29f71ef955L, EqualExpression);
    builder.put(0x2bba03e5041c9566L, ExpStatement);
    builder.put(0x2bba03e504172933L, Expression);
    builder.put(0x51b29a29f71ef958L, GreaterEqualExpression);
    builder.put(0x51b29a29f71ef956L, GreaterThanExpression);
    builder.put(0x51b29a29f711ee17L, IfStatement);
    builder.put(0x9729f9cf4175702L, IntegerLiteral);
    builder.put(0x9729f9cf414b638L, Istatement);
    builder.put(0x51b29a29f71ef959L, LowerEqualExpression);
    builder.put(0x51b29a29f71ef957L, LowerToExpression);
    builder.put(0x1686c41a5d838c0eL, Main);
    builder.put(0x2bba03e50417e568L, MinusExpression);
    builder.put(0x2bba03e50417f990L, MulExpression);
    builder.put(0x51b29a29f71ef95aL, NotEqualExpression);
    builder.put(0x2bba03e50417da21L, PlusExpression);
    builder.put(0x3d8a40f98056a6f4L, StatementContainer);
    builder.put(0x9729f9cf414ac3aL, Variable);
    builder.put(0x3d8a40f9803cffa2L, VariableReference);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
