package TestLanguage.interpreter.plugin;

/*Generated by MPS */

import com.mbeddr.mpsutil.interpreter.rt.InterpreterEvaluationHelper;
import org.jetbrains.mps.openapi.model.SNode;

public class TestEvalhelper {
  private static InterpreterEvaluationHelper testhelper = new InterpreterEvaluationHelper("test-interpreter");

  public static String eval(SNode n) {

    try {
      Object result = testhelper.evaluate(n);
      if (result != null) {

        return String.valueOf(result);
      } else {
        return "Null Statement";
      }

    } catch (Exception e) {
      return String.valueOf(e);
    }
  }
}
