package TestLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AssertStatement = 0;
  public static final int TestCase = 1;
  public static final int TestSuite = 2;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xe1e1e1ca38f54b3aL, 0xbc4e629f7e2e7b1bL);
    builder.put(0x3d8a40f98038c4f6L, AssertStatement);
    builder.put(0x3d8a40f9803499d7L, TestCase);
    builder.put(0x3d8a40f9803499d4L, TestSuite);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
