package LanguageIns.model;

/*Generated by MPS */


public class Exercise 5 {
  public static void Main() {
    int Variable1 = 6;
    boolean Variable2 = true;
    int Variable3 = 3 + 3;
    int Variable4 = Variable1;<!TextGen not found for 'NewLang.structure.NotEqualExpression'!><!TextGen not found for 'NewLang.structure.NotEqualExpression'!><!TextGen not found for 'NewLang.structure.NotEqualExpression'!><!TextGen not found for 'NewLang.structure.EqualExpression'!><!TextGen not found for 'NewLang.structure.GreaterEqualExpression'!>
  }
}
